package resolver

// Filter provides the ability to filter out sql generated by resolver.
type Filter func(fld *Field) bool

// GetFilter get unified filter from list of filters.
func GetFilter(filters ...Filter) Filter {
	return func(fld *Field) bool {
		for _, fr := range filters {
			if fr(fld) {
				return true
			}
		}

		return len(filters) == 0
	}
}
