openapi: 3.0.3
info:
  title: Wikimedia Enterprise API
  description: OpenAPI 3.0 specification for the On-demand, Snapshot, Realtime, and Realtime Batch API(s) of WME.
  version: 2.0.0
servers:
  - url: https://api.enterprise.wikimedia.com
security:
  - bearerAuth: []
