// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.17.3
// source: textprocessor.proto

package textprocessor

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// DictionaryRequest request params for GetDictionaryWords.
type DictionaryRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Language string   `protobuf:"bytes,1,opt,name=language,proto3" json:"language,omitempty"`
	Tokens   []string `protobuf:"bytes,2,rep,name=tokens,proto3" json:"tokens,omitempty"`
}

func (x *DictionaryRequest) Reset() {
	*x = DictionaryRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_textprocessor_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DictionaryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DictionaryRequest) ProtoMessage() {}

func (x *DictionaryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_textprocessor_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DictionaryRequest.ProtoReflect.Descriptor instead.
func (*DictionaryRequest) Descriptor() ([]byte, []int) {
	return file_textprocessor_proto_rawDescGZIP(), []int{0}
}

func (x *DictionaryRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *DictionaryRequest) GetTokens() []string {
	if x != nil {
		return x.Tokens
	}
	return nil
}

// DictionaryResponse response of GetDictionaryWords.
type DictionaryResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	DictWords    []string `protobuf:"bytes,1,rep,name=dictWords,proto3" json:"dictWords,omitempty"`
	NonDictWords []string `protobuf:"bytes,2,rep,name=nonDictWords,proto3" json:"nonDictWords,omitempty"`
}

func (x *DictionaryResponse) Reset() {
	*x = DictionaryResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_textprocessor_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *DictionaryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DictionaryResponse) ProtoMessage() {}

func (x *DictionaryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_textprocessor_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DictionaryResponse.ProtoReflect.Descriptor instead.
func (*DictionaryResponse) Descriptor() ([]byte, []int) {
	return file_textprocessor_proto_rawDescGZIP(), []int{1}
}

func (x *DictionaryResponse) GetDictWords() []string {
	if x != nil {
		return x.DictWords
	}
	return nil
}

func (x *DictionaryResponse) GetNonDictWords() []string {
	if x != nil {
		return x.NonDictWords
	}
	return nil
}

// NonSafeRequest request params for GetNonSafeWords.
type NonSafeRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Language string   `protobuf:"bytes,1,opt,name=language,proto3" json:"language,omitempty"`
	Tokens   []string `protobuf:"bytes,2,rep,name=tokens,proto3" json:"tokens,omitempty"`
}

func (x *NonSafeRequest) Reset() {
	*x = NonSafeRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_textprocessor_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NonSafeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NonSafeRequest) ProtoMessage() {}

func (x *NonSafeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_textprocessor_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NonSafeRequest.ProtoReflect.Descriptor instead.
func (*NonSafeRequest) Descriptor() ([]byte, []int) {
	return file_textprocessor_proto_rawDescGZIP(), []int{2}
}

func (x *NonSafeRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *NonSafeRequest) GetTokens() []string {
	if x != nil {
		return x.Tokens
	}
	return nil
}

// NonSafeResponse response of GetNonSafeWords.
type NonSafeResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NonSafeWords []string `protobuf:"bytes,1,rep,name=nonSafeWords,proto3" json:"nonSafeWords,omitempty"`
}

func (x *NonSafeResponse) Reset() {
	*x = NonSafeResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_textprocessor_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *NonSafeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NonSafeResponse) ProtoMessage() {}

func (x *NonSafeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_textprocessor_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NonSafeResponse.ProtoReflect.Descriptor instead.
func (*NonSafeResponse) Descriptor() ([]byte, []int) {
	return file_textprocessor_proto_rawDescGZIP(), []int{3}
}

func (x *NonSafeResponse) GetNonSafeWords() []string {
	if x != nil {
		return x.NonSafeWords
	}
	return nil
}

// InformalRequest request params for GetInformalWords.
type InformalRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Language string   `protobuf:"bytes,1,opt,name=language,proto3" json:"language,omitempty"`
	Tokens   []string `protobuf:"bytes,2,rep,name=tokens,proto3" json:"tokens,omitempty"`
}

func (x *InformalRequest) Reset() {
	*x = InformalRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_textprocessor_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InformalRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InformalRequest) ProtoMessage() {}

func (x *InformalRequest) ProtoReflect() protoreflect.Message {
	mi := &file_textprocessor_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InformalRequest.ProtoReflect.Descriptor instead.
func (*InformalRequest) Descriptor() ([]byte, []int) {
	return file_textprocessor_proto_rawDescGZIP(), []int{4}
}

func (x *InformalRequest) GetLanguage() string {
	if x != nil {
		return x.Language
	}
	return ""
}

func (x *InformalRequest) GetTokens() []string {
	if x != nil {
		return x.Tokens
	}
	return nil
}

// InformalResponse response of GetInformalWords.
type InformalResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InformalWords []string `protobuf:"bytes,1,rep,name=informalWords,proto3" json:"informalWords,omitempty"`
}

func (x *InformalResponse) Reset() {
	*x = InformalResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_textprocessor_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *InformalResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InformalResponse) ProtoMessage() {}

func (x *InformalResponse) ProtoReflect() protoreflect.Message {
	mi := &file_textprocessor_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InformalResponse.ProtoReflect.Descriptor instead.
func (*InformalResponse) Descriptor() ([]byte, []int) {
	return file_textprocessor_proto_rawDescGZIP(), []int{5}
}

func (x *InformalResponse) GetInformalWords() []string {
	if x != nil {
		return x.InformalWords
	}
	return nil
}

// UppercaseRequest request params for GetUpperCaseWords.
type UppercaseRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Tokens []string `protobuf:"bytes,1,rep,name=tokens,proto3" json:"tokens,omitempty"`
}

func (x *UppercaseRequest) Reset() {
	*x = UppercaseRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_textprocessor_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UppercaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UppercaseRequest) ProtoMessage() {}

func (x *UppercaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_textprocessor_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UppercaseRequest.ProtoReflect.Descriptor instead.
func (*UppercaseRequest) Descriptor() ([]byte, []int) {
	return file_textprocessor_proto_rawDescGZIP(), []int{6}
}

func (x *UppercaseRequest) GetTokens() []string {
	if x != nil {
		return x.Tokens
	}
	return nil
}

// UppercaseResponse response of GetUpperCaseWords.
type UppercaseResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	UppercaseWords []string `protobuf:"bytes,1,rep,name=uppercaseWords,proto3" json:"uppercaseWords,omitempty"`
}

func (x *UppercaseResponse) Reset() {
	*x = UppercaseResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_textprocessor_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UppercaseResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UppercaseResponse) ProtoMessage() {}

func (x *UppercaseResponse) ProtoReflect() protoreflect.Message {
	mi := &file_textprocessor_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UppercaseResponse.ProtoReflect.Descriptor instead.
func (*UppercaseResponse) Descriptor() ([]byte, []int) {
	return file_textprocessor_proto_rawDescGZIP(), []int{7}
}

func (x *UppercaseResponse) GetUppercaseWords() []string {
	if x != nil {
		return x.UppercaseWords
	}
	return nil
}

var File_textprocessor_proto protoreflect.FileDescriptor

var file_textprocessor_proto_rawDesc = []byte{
	0x0a, 0x13, 0x74, 0x65, 0x78, 0x74, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x74, 0x65, 0x78, 0x74, 0x70, 0x72, 0x6f, 0x63, 0x65,
	0x73, 0x73, 0x6f, 0x72, 0x22, 0x47, 0x0a, 0x11, 0x44, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61,
	0x72, 0x79, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x6e,
	0x67, 0x75, 0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x6e,
	0x67, 0x75, 0x61, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x73, 0x18,
	0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x73, 0x22, 0x56, 0x0a,
	0x12, 0x44, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x52, 0x65, 0x73, 0x70, 0x6f,
	0x6e, 0x73, 0x65, 0x12, 0x1c, 0x0a, 0x09, 0x64, 0x69, 0x63, 0x74, 0x57, 0x6f, 0x72, 0x64, 0x73,
	0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x09, 0x64, 0x69, 0x63, 0x74, 0x57, 0x6f, 0x72, 0x64,
	0x73, 0x12, 0x22, 0x0a, 0x0c, 0x6e, 0x6f, 0x6e, 0x44, 0x69, 0x63, 0x74, 0x57, 0x6f, 0x72, 0x64,
	0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0c, 0x6e, 0x6f, 0x6e, 0x44, 0x69, 0x63, 0x74,
	0x57, 0x6f, 0x72, 0x64, 0x73, 0x22, 0x44, 0x0a, 0x0e, 0x4e, 0x6f, 0x6e, 0x53, 0x61, 0x66, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75,
	0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75,
	0x61, 0x67, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x73, 0x18, 0x02, 0x20,
	0x03, 0x28, 0x09, 0x52, 0x06, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x73, 0x22, 0x35, 0x0a, 0x0f, 0x4e,
	0x6f, 0x6e, 0x53, 0x61, 0x66, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x22,
	0x0a, 0x0c, 0x6e, 0x6f, 0x6e, 0x53, 0x61, 0x66, 0x65, 0x57, 0x6f, 0x72, 0x64, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x0c, 0x6e, 0x6f, 0x6e, 0x53, 0x61, 0x66, 0x65, 0x57, 0x6f, 0x72,
	0x64, 0x73, 0x22, 0x45, 0x0a, 0x0f, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x52, 0x65,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67,
	0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x61, 0x6e, 0x67, 0x75, 0x61, 0x67,
	0x65, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28,
	0x09, 0x52, 0x06, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x73, 0x22, 0x38, 0x0a, 0x10, 0x49, 0x6e, 0x66,
	0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x24, 0x0a,
	0x0d, 0x69, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x57, 0x6f, 0x72, 0x64, 0x73, 0x18, 0x01,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x0d, 0x69, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x57, 0x6f,
	0x72, 0x64, 0x73, 0x22, 0x2a, 0x0a, 0x10, 0x55, 0x70, 0x70, 0x65, 0x72, 0x63, 0x61, 0x73, 0x65,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x16, 0x0a, 0x06, 0x74, 0x6f, 0x6b, 0x65, 0x6e,
	0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x73, 0x22,
	0x3b, 0x0a, 0x11, 0x55, 0x70, 0x70, 0x65, 0x72, 0x63, 0x61, 0x73, 0x65, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x12, 0x26, 0x0a, 0x0e, 0x75, 0x70, 0x70, 0x65, 0x72, 0x63, 0x61, 0x73,
	0x65, 0x57, 0x6f, 0x72, 0x64, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0e, 0x75, 0x70,
	0x70, 0x65, 0x72, 0x63, 0x61, 0x73, 0x65, 0x57, 0x6f, 0x72, 0x64, 0x73, 0x32, 0xe9, 0x02, 0x0a,
	0x0d, 0x54, 0x65, 0x78, 0x74, 0x50, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x12, 0x59,
	0x0a, 0x12, 0x47, 0x65, 0x74, 0x44, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x57,
	0x6f, 0x72, 0x64, 0x73, 0x12, 0x20, 0x2e, 0x74, 0x65, 0x78, 0x74, 0x70, 0x72, 0x6f, 0x63, 0x65,
	0x73, 0x73, 0x6f, 0x72, 0x2e, 0x44, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72, 0x79, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x21, 0x2e, 0x74, 0x65, 0x78, 0x74, 0x70, 0x72, 0x6f,
	0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x2e, 0x44, 0x69, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x72,
	0x79, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x50, 0x0a, 0x0f, 0x47, 0x65, 0x74,
	0x4e, 0x6f, 0x6e, 0x53, 0x61, 0x66, 0x65, 0x57, 0x6f, 0x72, 0x64, 0x73, 0x12, 0x1d, 0x2e, 0x74,
	0x65, 0x78, 0x74, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x2e, 0x4e, 0x6f, 0x6e,
	0x53, 0x61, 0x66, 0x65, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x1e, 0x2e, 0x74, 0x65,
	0x78, 0x74, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x2e, 0x4e, 0x6f, 0x6e, 0x53,
	0x61, 0x66, 0x65, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x53, 0x0a, 0x10, 0x47,
	0x65, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x57, 0x6f, 0x72, 0x64, 0x73, 0x12,
	0x1e, 0x2e, 0x74, 0x65, 0x78, 0x74, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x2e,
	0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a,
	0x1f, 0x2e, 0x74, 0x65, 0x78, 0x74, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x2e,
	0x49, 0x6e, 0x66, 0x6f, 0x72, 0x6d, 0x61, 0x6c, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x56, 0x0a, 0x11, 0x47, 0x65, 0x74, 0x55, 0x70, 0x70, 0x65, 0x72, 0x43, 0x61, 0x73, 0x65,
	0x57, 0x6f, 0x72, 0x64, 0x73, 0x12, 0x1f, 0x2e, 0x74, 0x65, 0x78, 0x74, 0x70, 0x72, 0x6f, 0x63,
	0x65, 0x73, 0x73, 0x6f, 0x72, 0x2e, 0x55, 0x70, 0x70, 0x65, 0x72, 0x63, 0x61, 0x73, 0x65, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x20, 0x2e, 0x74, 0x65, 0x78, 0x74, 0x70, 0x72, 0x6f,
	0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x2e, 0x55, 0x70, 0x70, 0x65, 0x72, 0x63, 0x61, 0x73, 0x65,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x42, 0x12, 0x5a, 0x10, 0x2e, 0x2f, 0x3b, 0x74,
	0x65, 0x78, 0x74, 0x70, 0x72, 0x6f, 0x63, 0x65, 0x73, 0x73, 0x6f, 0x72, 0x62, 0x06, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_textprocessor_proto_rawDescOnce sync.Once
	file_textprocessor_proto_rawDescData = file_textprocessor_proto_rawDesc
)

func file_textprocessor_proto_rawDescGZIP() []byte {
	file_textprocessor_proto_rawDescOnce.Do(func() {
		file_textprocessor_proto_rawDescData = protoimpl.X.CompressGZIP(file_textprocessor_proto_rawDescData)
	})
	return file_textprocessor_proto_rawDescData
}

var file_textprocessor_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_textprocessor_proto_goTypes = []interface{}{
	(*DictionaryRequest)(nil),  // 0: textprocessor.DictionaryRequest
	(*DictionaryResponse)(nil), // 1: textprocessor.DictionaryResponse
	(*NonSafeRequest)(nil),     // 2: textprocessor.NonSafeRequest
	(*NonSafeResponse)(nil),    // 3: textprocessor.NonSafeResponse
	(*InformalRequest)(nil),    // 4: textprocessor.InformalRequest
	(*InformalResponse)(nil),   // 5: textprocessor.InformalResponse
	(*UppercaseRequest)(nil),   // 6: textprocessor.UppercaseRequest
	(*UppercaseResponse)(nil),  // 7: textprocessor.UppercaseResponse
}
var file_textprocessor_proto_depIdxs = []int32{
	0, // 0: textprocessor.TextProcessor.GetDictionaryWords:input_type -> textprocessor.DictionaryRequest
	2, // 1: textprocessor.TextProcessor.GetNonSafeWords:input_type -> textprocessor.NonSafeRequest
	4, // 2: textprocessor.TextProcessor.GetInformalWords:input_type -> textprocessor.InformalRequest
	6, // 3: textprocessor.TextProcessor.GetUpperCaseWords:input_type -> textprocessor.UppercaseRequest
	1, // 4: textprocessor.TextProcessor.GetDictionaryWords:output_type -> textprocessor.DictionaryResponse
	3, // 5: textprocessor.TextProcessor.GetNonSafeWords:output_type -> textprocessor.NonSafeResponse
	5, // 6: textprocessor.TextProcessor.GetInformalWords:output_type -> textprocessor.InformalResponse
	7, // 7: textprocessor.TextProcessor.GetUpperCaseWords:output_type -> textprocessor.UppercaseResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_textprocessor_proto_init() }
func file_textprocessor_proto_init() {
	if File_textprocessor_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_textprocessor_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DictionaryRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_textprocessor_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*DictionaryResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_textprocessor_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NonSafeRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_textprocessor_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*NonSafeResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_textprocessor_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InformalRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_textprocessor_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*InformalResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_textprocessor_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UppercaseRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_textprocessor_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UppercaseResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_textprocessor_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_textprocessor_proto_goTypes,
		DependencyIndexes: file_textprocessor_proto_depIdxs,
		MessageInfos:      file_textprocessor_proto_msgTypes,
	}.Build()
	File_textprocessor_proto = out.File
	file_textprocessor_proto_rawDesc = nil
	file_textprocessor_proto_goTypes = nil
	file_textprocessor_proto_depIdxs = nil
}
