# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pipelines/protos/admin.proto
# Protobuf Python Version: 4.25.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cpipelines/protos/admin.proto\x12\x05\x61\x64min\"G\n\x11\x41rticleIdentifier\x12\x10\n\x08\x64\x61tabase\x18\x01 \x01(\t\x12\x11\n\tnamespace\x18\x02 \x01(\x05\x12\r\n\x05title\x18\x03 \x01(\t\"c\n\x17\x41rticleProcessingResult\x12)\n\x07\x61rticle\x18\x01 \x01(\x0b\x32\x18.admin.ArticleIdentifier\x12\x0e\n\x06status\x18\x02 \x01(\x05\x12\r\n\x05\x65rror\x18\x03 \x01(\t\";\n\rDeleteRequest\x12*\n\x08\x61rticles\x18\x01 \x03(\x0b\x32\x18.admin.ArticleIdentifier\"A\n\x0e\x44\x65leteResponse\x12/\n\x07results\x18\x01 \x03(\x0b\x32\x1e.admin.ArticleProcessingResult\"<\n\x0eRefreshRequest\x12*\n\x08\x61rticles\x18\x01 \x03(\x0b\x32\x18.admin.ArticleIdentifier\"B\n\x0fRefreshResponse\x12/\n\x07results\x18\x01 \x03(\x0b\x32\x1e.admin.ArticleProcessingResult2x\n\x05\x41\x64min\x12\x35\n\x06\x44\x65lete\x12\x14.admin.DeleteRequest\x1a\x15.admin.DeleteResponse\x12\x38\n\x07Refresh\x12\x15.admin.RefreshRequest\x1a\x16.admin.RefreshResponseB\x0bZ\t./;protosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pipelines.protos.admin_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:
  _globals['DESCRIPTOR']._options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\t./;protos'
  _globals['_ARTICLEIDENTIFIER']._serialized_start=39
  _globals['_ARTICLEIDENTIFIER']._serialized_end=110
  _globals['_ARTICLEPROCESSINGRESULT']._serialized_start=112
  _globals['_ARTICLEPROCESSINGRESULT']._serialized_end=211
  _globals['_DELETEREQUEST']._serialized_start=213
  _globals['_DELETEREQUEST']._serialized_end=272
  _globals['_DELETERESPONSE']._serialized_start=274
  _globals['_DELETERESPONSE']._serialized_end=339
  _globals['_REFRESHREQUEST']._serialized_start=341
  _globals['_REFRESHREQUEST']._serialized_end=401
  _globals['_REFRESHRESPONSE']._serialized_start=403
  _globals['_REFRESHRESPONSE']._serialized_end=469
  _globals['_ADMIN']._serialized_start=471
  _globals['_ADMIN']._serialized_end=591
# @@protoc_insertion_point(module_scope)
