openapi: "3.0.3"
info:
  title: Wikimedia Enterprise Authentication API
  description: Authentication API for WME API suite.
  version: v1
servers:
  - url: http://localhost:4050
    description: Localhost
  - url: https://auth.enterprisewikimedia.com
    description: Production
  - url: https://auth-dv.enterprisewikimedia.com
    description: Development
paths:
  /v1/login:
    post:
      summary: Receive auth tokens in exchange for username and password.
      description: By receiving username and password creates new access, id and refresh tokens.
      tags:
        - login
      operationId: v1-login
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: admin
                password:
                  type: string
                  example: j8BDWYrQwDF5u4Yu
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/login"
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
        422:
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
  /v1/token-refresh:
    post:
      summary: Receive auth tokens by providing refresh token.
      description: By receiving refresh token and username provides new access and id tokens.
      tags:
        - token
      operationId: v1-token-refresh
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: admin
                refresh_token:
                  type: string
                  example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/refresh-token"
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
        403:
          description: Forbidden
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
        422:
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
  /v1/token-revoke:
    post:
      summary: Revokes all of the access tokens generated by the specified refresh token.
      description: By receiving refresh token revokes access for all of its access tokens. After the token is revoked, you can not use the revoked token to access authenticated APIs.
      tags:
        - token
      operationId: v1-token-revoke
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                refresh_token:
                  type: string
                  example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9
      responses:
        204:
          description: Token was successfully revoked.
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
        422:
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
  /v1/forgot-password:
    post:
      summary: Initiates forgot password flow for specified user.
      description: By receiving username sends confirmation code that is required to change the user's password (look into `/v1/forgot-password-confirm`).
      tags:
        - forgot password
      operationId: v1-forgot-password
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: admin
      responses:
        204:
          description: Confirmation code sent successfully.
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
        422:
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
  /v1/forgot-password-confirm:
    post:
      summary: Changes user password as a part of forgot password flow.
      description: By receiving username, new password and confirmation code (see `/v1/forgot-password`) changes user password.
      tags:
        - forgot password
      operationId: v1-forgot-password-confirm
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: admin
                password:
                  type: string
                  example: j8BDWYrQwDF5u4Yu
                confirmation_code:
                  type: string
                  example: 6MadrbRF
      responses:
        204:
          description: Password reset successfully.
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
        422:
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
  /v1/change-password:
    post:
      summary: Changes user password.
      description: Changes user password by receiving username and old password.
      tags:
        - change password
      operationId: v1-change-password
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                access_token:
                  type: string
                  example: sInR5cCI6IkpXVCJ9eyJhbGciOiJIUzI1NiI
                previous_password:
                  type: string
                  example: j8BDWYrQwDF5u4Yu
                proposed_password:
                  type: string
                  example: b2BDWZrQwDF5u4Yu
      responses:
        204:
          description: Successful password change .
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
        422:
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
  /v1/new-password-required:
    post:
      summary: Respond to new password required challenge.
      description: Responds `NEW_PASSWORD_REQUIRED` challenge by receiving username and session token and setting new password.
      tags:
        - new password required
      operationId: v1-new-password-required
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                session:
                  type: string
                  example: eyJhbGcisInR5cCI6IkOiJIUzI1NiIpXVCJ9
                username:
                  type: string
                  example: admin
                new_password:
                  type: string
                  example: b2BDWZrQwDF5u4Yu
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/new-password-required"
        401:
          description: Unauthorized
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
        422:
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
  /v1/create-user:
    post:
      summary: Creates a user with the given parameters.
      description: Creates a user and attaches it to the free tier group.
      tags:
        - create user
      operationId: v1-create-user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: user_name
                email:
                  type: string
                  example: email@email.com
                password:
                  type: string
                captcha_id:
                  type: string
                  example: j8BDWYrQwDF5u4Yu
                captcha_solution:
                  type: string
                  exmaple: 123569
      responses:
        204:
          description: No Content
        422:
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
  /v1/confirm-user:
    post:
      summary: Confirms a user.
      description: Confirms a user by a given confirmation code.
      tags:
        - confirm user
      operationId: v1-confirm-user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                  example: admin
                confirmation_code:
                  type: string
                  example: 324523
      responses:
        204:
          description: No Content
        422:
          description: Unprocessable Entity
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
  /v1/captcha:
    get:
      summary: Generates new captcha.
      description: Generates new captcha identifier and random solution.
      tags:
        - captcha
      operationId: v1-captcha
      responses:
        200:
          description: OK
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/captcha"
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
  /v1/captcha/{identifier}:
    get:
      summary: Generates captcha image.
      description: Generates captcha solution image by provided identifier.
      tags:
        - captcha
      operationId: v1-captcha-id
      parameters:
        - in: path
          name: identifier
          required: true
          schema:
            type: string
            minimum: 1
          description: Captcha identifier
      responses:
        200:
          description: OK
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/error"
components:
  schemas:
    error:
      properties:
        message:
          type: string
        status:
          type: integer
      type: object
    login:
      properties:
        challenge_name:
          type: string
        id_token:
          type: string
        access_token:
          type: string
        refresh_token:
          type: string
        session:
          type: string
        expires_in:
          type: integer
          example: 300
      type: object
    refresh-token:
      properties:
        id_token:
          type: string
        access_token:
          type: string
        expires_in:
          type: integer
          example: 300
      type: object
    new-password-required:
      properties:
        id_token:
          type: string
        access_token:
          type: string
        refresh_token:
          type: string
        session:
          type: string
        expires_in:
          type: integer
          example: 300
      type: object
    captcha:
      properties:
        identifier:
          type: string
      type: object
