# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from pipelines.protos import bulk_pb2 as pipelines_dot_protos_dot_bulk__pb2


class BulkStub(object):
    """Bulk service method definitions.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Projects = channel.unary_unary(
                '/bulk.Bulk/Projects',
                request_serializer=pipelines_dot_protos_dot_bulk__pb2.ProjectsRequest.SerializeToString,
                response_deserializer=pipelines_dot_protos_dot_bulk__pb2.ProjectsResponse.FromString,
                )
        self.Namespaces = channel.unary_unary(
                '/bulk.Bulk/Namespaces',
                request_serializer=pipelines_dot_protos_dot_bulk__pb2.NamespacesRequest.SerializeToString,
                response_deserializer=pipelines_dot_protos_dot_bulk__pb2.NamespacesResponse.FromString,
                )
        self.Articles = channel.unary_unary(
                '/bulk.Bulk/Articles',
                request_serializer=pipelines_dot_protos_dot_bulk__pb2.ArticlesRequest.SerializeToString,
                response_deserializer=pipelines_dot_protos_dot_bulk__pb2.ArticlesResponse.FromString,
                )


class BulkServicer(object):
    """Bulk service method definitions.
    """

    def Projects(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Namespaces(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Articles(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BulkServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Projects': grpc.unary_unary_rpc_method_handler(
                    servicer.Projects,
                    request_deserializer=pipelines_dot_protos_dot_bulk__pb2.ProjectsRequest.FromString,
                    response_serializer=pipelines_dot_protos_dot_bulk__pb2.ProjectsResponse.SerializeToString,
            ),
            'Namespaces': grpc.unary_unary_rpc_method_handler(
                    servicer.Namespaces,
                    request_deserializer=pipelines_dot_protos_dot_bulk__pb2.NamespacesRequest.FromString,
                    response_serializer=pipelines_dot_protos_dot_bulk__pb2.NamespacesResponse.SerializeToString,
            ),
            'Articles': grpc.unary_unary_rpc_method_handler(
                    servicer.Articles,
                    request_deserializer=pipelines_dot_protos_dot_bulk__pb2.ArticlesRequest.FromString,
                    response_serializer=pipelines_dot_protos_dot_bulk__pb2.ArticlesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'bulk.Bulk', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Bulk(object):
    """Bulk service method definitions.
    """

    @staticmethod
    def Projects(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bulk.Bulk/Projects',
            pipelines_dot_protos_dot_bulk__pb2.ProjectsRequest.SerializeToString,
            pipelines_dot_protos_dot_bulk__pb2.ProjectsResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Namespaces(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bulk.Bulk/Namespaces',
            pipelines_dot_protos_dot_bulk__pb2.NamespacesRequest.SerializeToString,
            pipelines_dot_protos_dot_bulk__pb2.NamespacesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def Articles(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/bulk.Bulk/Articles',
            pipelines_dot_protos_dot_bulk__pb2.ArticlesRequest.SerializeToString,
            pipelines_dot_protos_dot_bulk__pb2.ArticlesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
