# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pipelines/protos/hourlys.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1epipelines/protos/hourlys.proto\x12\x07hourlys\"f\n\rExportRequest\x12\x11\n\tnamespace\x18\x01 \x01(\x05\x12\x0f\n\x07workers\x18\x02 \x01(\x05\x12\x0f\n\x07project\x18\x03 \x01(\t\x12\x0e\n\x06prefix\x18\x04 \x01(\t\x12\x10\n\x08language\x18\x05 \x01(\t\"/\n\x0e\x45xportResponse\x12\r\n\x05total\x18\x01 \x01(\x05\x12\x0e\n\x06\x65rrors\x18\x02 \x01(\x05\"5\n\x0bTidyRequest\x12\x16\n\x0eretention_days\x18\x01 \x01(\x05\x12\x0e\n\x06prefix\x18\x02 \x01(\t\"-\n\x0cTidyResponse\x12\r\n\x05total\x18\x01 \x01(\x05\x12\x0e\n\x06\x65rrors\x18\x02 \x01(\x05\"\"\n\x10\x41ggregateRequest\x12\x0e\n\x06prefix\x18\x01 \x01(\t\"2\n\x11\x41ggregateResponse\x12\r\n\x05total\x18\x01 \x01(\x05\x12\x0e\n\x06\x65rrors\x18\x02 \x01(\x05\x32\xbd\x01\n\x07Hourlys\x12\x39\n\x06\x45xport\x12\x16.hourlys.ExportRequest\x1a\x17.hourlys.ExportResponse\x12\x33\n\x04Tidy\x12\x14.hourlys.TidyRequest\x1a\x15.hourlys.TidyResponse\x12\x42\n\tAggregate\x12\x19.hourlys.AggregateRequest\x1a\x1a.hourlys.AggregateResponseB\x0bZ\t./;protosb\x06proto3')



_EXPORTREQUEST = DESCRIPTOR.message_types_by_name['ExportRequest']
_EXPORTRESPONSE = DESCRIPTOR.message_types_by_name['ExportResponse']
_TIDYREQUEST = DESCRIPTOR.message_types_by_name['TidyRequest']
_TIDYRESPONSE = DESCRIPTOR.message_types_by_name['TidyResponse']
_AGGREGATEREQUEST = DESCRIPTOR.message_types_by_name['AggregateRequest']
_AGGREGATERESPONSE = DESCRIPTOR.message_types_by_name['AggregateResponse']
ExportRequest = _reflection.GeneratedProtocolMessageType('ExportRequest', (_message.Message,), {
  'DESCRIPTOR' : _EXPORTREQUEST,
  '__module__' : 'pipelines.protos.hourlys_pb2'
  # @@protoc_insertion_point(class_scope:hourlys.ExportRequest)
  })
_sym_db.RegisterMessage(ExportRequest)

ExportResponse = _reflection.GeneratedProtocolMessageType('ExportResponse', (_message.Message,), {
  'DESCRIPTOR' : _EXPORTRESPONSE,
  '__module__' : 'pipelines.protos.hourlys_pb2'
  # @@protoc_insertion_point(class_scope:hourlys.ExportResponse)
  })
_sym_db.RegisterMessage(ExportResponse)

TidyRequest = _reflection.GeneratedProtocolMessageType('TidyRequest', (_message.Message,), {
  'DESCRIPTOR' : _TIDYREQUEST,
  '__module__' : 'pipelines.protos.hourlys_pb2'
  # @@protoc_insertion_point(class_scope:hourlys.TidyRequest)
  })
_sym_db.RegisterMessage(TidyRequest)

TidyResponse = _reflection.GeneratedProtocolMessageType('TidyResponse', (_message.Message,), {
  'DESCRIPTOR' : _TIDYRESPONSE,
  '__module__' : 'pipelines.protos.hourlys_pb2'
  # @@protoc_insertion_point(class_scope:hourlys.TidyResponse)
  })
_sym_db.RegisterMessage(TidyResponse)

AggregateRequest = _reflection.GeneratedProtocolMessageType('AggregateRequest', (_message.Message,), {
  'DESCRIPTOR' : _AGGREGATEREQUEST,
  '__module__' : 'pipelines.protos.hourlys_pb2'
  # @@protoc_insertion_point(class_scope:hourlys.AggregateRequest)
  })
_sym_db.RegisterMessage(AggregateRequest)

AggregateResponse = _reflection.GeneratedProtocolMessageType('AggregateResponse', (_message.Message,), {
  'DESCRIPTOR' : _AGGREGATERESPONSE,
  '__module__' : 'pipelines.protos.hourlys_pb2'
  # @@protoc_insertion_point(class_scope:hourlys.AggregateResponse)
  })
_sym_db.RegisterMessage(AggregateResponse)

_HOURLYS = DESCRIPTOR.services_by_name['Hourlys']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\t./;protos'
  _EXPORTREQUEST._serialized_start=43
  _EXPORTREQUEST._serialized_end=145
  _EXPORTRESPONSE._serialized_start=147
  _EXPORTRESPONSE._serialized_end=194
  _TIDYREQUEST._serialized_start=196
  _TIDYREQUEST._serialized_end=249
  _TIDYRESPONSE._serialized_start=251
  _TIDYRESPONSE._serialized_end=296
  _AGGREGATEREQUEST._serialized_start=298
  _AGGREGATEREQUEST._serialized_end=332
  _AGGREGATERESPONSE._serialized_start=334
  _AGGREGATERESPONSE._serialized_end=384
  _HOURLYS._serialized_start=387
  _HOURLYS._serialized_end=576
# @@protoc_insertion_point(module_scope)
