# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: pipelines/protos/snapshots.proto
# Protobuf Python Version: 5.26.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n pipelines/protos/snapshots.proto\x12\tsnapshots\"\xb4\x01\n\rExportRequest\x12\x11\n\tnamespace\x18\x01 \x01(\x05\x12\x0f\n\x07workers\x18\x02 \x01(\x05\x12\x0f\n\x07project\x18\x03 \x01(\t\x12\x0e\n\x06prefix\x18\x04 \x01(\t\x12\x10\n\x08language\x18\x05 \x01(\t\x12\r\n\x05since\x18\x06 \x01(\x03\x12\x16\n\x0e\x65xclude_events\x18\x07 \x03(\t\x12\x0c\n\x04type\x18\x08 \x01(\t\x12\x17\n\x0f\x65nable_chunking\x18\t \x01(\x08\"/\n\x0e\x45xportResponse\x12\r\n\x05total\x18\x01 \x01(\x05\x12\x0e\n\x06\x65rrors\x18\x02 \x01(\x05\"C\n\x0b\x43opyRequest\x12\x0f\n\x07workers\x18\x01 \x01(\x05\x12\x10\n\x08projects\x18\x02 \x03(\t\x12\x11\n\tnamespace\x18\x03 \x01(\x05\"-\n\x0c\x43opyResponse\x12\r\n\x05total\x18\x01 \x01(\x05\x12\x0e\n\x06\x65rrors\x18\x02 \x01(\x05\"C\n\x10\x41ggregateRequest\x12\x0e\n\x06prefix\x18\x01 \x01(\t\x12\r\n\x05since\x18\x02 \x01(\x03\x12\x10\n\x08snapshot\x18\x03 \x01(\t\"2\n\x11\x41ggregateResponse\x12\r\n\x05total\x18\x01 \x01(\x05\x12\x0e\n\x06\x65rrors\x18\x02 \x01(\x05\"\x16\n\x14\x41ggregateCopyRequest\"6\n\x15\x41ggregateCopyResponse\x12\r\n\x05total\x18\x01 \x01(\x05\x12\x0e\n\x06\x65rrors\x18\x02 \x01(\x05\">\n\x17\x41ggregateCommonsRequest\x12\x0e\n\x06prefix\x18\x01 \x01(\t\x12\x13\n\x0btime_period\x18\x02 \x01(\t\"9\n\x18\x41ggregateCommonsResponse\x12\r\n\x05total\x18\x01 \x01(\x05\x12\x0e\n\x06\x65rrors\x18\x02 \x01(\x05\x32\xfc\x02\n\tSnapshots\x12=\n\x06\x45xport\x12\x18.snapshots.ExportRequest\x1a\x19.snapshots.ExportResponse\x12\x37\n\x04\x43opy\x12\x16.snapshots.CopyRequest\x1a\x17.snapshots.CopyResponse\x12\x46\n\tAggregate\x12\x1b.snapshots.AggregateRequest\x1a\x1c.snapshots.AggregateResponse\x12R\n\rAggregateCopy\x12\x1f.snapshots.AggregateCopyRequest\x1a .snapshots.AggregateCopyResponse\x12[\n\x10\x41ggregateCommons\x12\".snapshots.AggregateCommonsRequest\x1a#.snapshots.AggregateCommonsResponseB\x0bZ\t./;protosb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'pipelines.protos.snapshots_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\t./;protos'
  _globals['_EXPORTREQUEST']._serialized_start=48
  _globals['_EXPORTREQUEST']._serialized_end=228
  _globals['_EXPORTRESPONSE']._serialized_start=230
  _globals['_EXPORTRESPONSE']._serialized_end=277
  _globals['_COPYREQUEST']._serialized_start=279
  _globals['_COPYREQUEST']._serialized_end=346
  _globals['_COPYRESPONSE']._serialized_start=348
  _globals['_COPYRESPONSE']._serialized_end=393
  _globals['_AGGREGATEREQUEST']._serialized_start=395
  _globals['_AGGREGATEREQUEST']._serialized_end=462
  _globals['_AGGREGATERESPONSE']._serialized_start=464
  _globals['_AGGREGATERESPONSE']._serialized_end=514
  _globals['_AGGREGATECOPYREQUEST']._serialized_start=516
  _globals['_AGGREGATECOPYREQUEST']._serialized_end=538
  _globals['_AGGREGATECOPYRESPONSE']._serialized_start=540
  _globals['_AGGREGATECOPYRESPONSE']._serialized_end=594
  _globals['_AGGREGATECOMMONSREQUEST']._serialized_start=596
  _globals['_AGGREGATECOMMONSREQUEST']._serialized_end=658
  _globals['_AGGREGATECOMMONSRESPONSE']._serialized_start=660
  _globals['_AGGREGATECOMMONSRESPONSE']._serialized_end=717
  _globals['_SNAPSHOTS']._serialized_start=720
  _globals['_SNAPSHOTS']._serialized_end=1100
# @@protoc_insertion_point(module_scope)
